#! spec.yaml
name: zero2pro
region: sfo3
services:
  - name: zero2prod
    image:
      registry_type: DOCKER_HUB
      registry: docker.io
      repository: opas350/zero2prod
    github:
      branch: main
      deploy_on_push: true
      repo: opas350/rust-zero-prod
    health_check:
      http_path: /health_check
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /